- command: subscription-manager repos --enable=rhel-server-rhscl-6-rpms

- name: Install Apache and PHP
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - php54
    - php54-php-cli
    - php54-php-common
    - php54-php-gd
    - php54-php-mbstring
    - php54-php
    - git

##- command: source /opt/rh/php54/enable

- name: IPTables for Apache
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- copy: src=/etc/ansible/roles/ndlc.info/files/httpd.conf dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=644

- name: Apache service state
  service: name=httpd state=started enabled=yes

