- command: /bin/chgrp -R apache /var/www/html/stage.ndlc.info
- command: bash -c "find /var/www/html/stage.ndlc.info -type f -print0 | xargs -0 chmod 664"
- command: bash -c "find /var/www/html/stage.ndlc.info -type d -print0 | xargs -0 chmod 775"
- command: bash -c "find /var/www/html/stage.ndlc.info -type d -print0 | xargs -0 chmod +s"
- copy: src=htaccess_git dest=/var/www/html/stage.ndlc.info/.git/.htaccess owner=root group=apache mode=0640
- copy: src=stage.ndlc.info.conf dest=/etc/httpd/conf.d/stage.ndlc.info.conf owner=root group=root mode=644
- name: restart Apache service state
  service: name=httpd state=restarted enabled=yes
